import { ConversionTask, DesktopSelfCheckItem } from "../shared/desktop-api";
import { ReaderLocale } from "../../../../src/ui/locale";

const ENGLISH = {
  appName: "Paper2MD",
  newExtraction: "New extraction",
  library: "Library",
  favorites: "Favorites",
  settings: "Settings",
  searchLibrary: "Search papers",
  allDocuments: "All documents",
  favoriteDocuments: "Favorite documents",
  chooseLibrary: "Choose library",
  changeLibrary: "Change library",
  revealLibrary: "Show in Explorer",
  noLibrary: "Choose a local Paper2MD library to see validated papers here.",
  emptyLibrary: "No validated papers are published in this library yet.",
  emptyFavorites: "Favorite papers will appear here.",
  noSearchResults: "No papers match this search.",
  libraryTruncated: "Showing the first 500 validated papers.",
  mineruDocument: "MinerU package",
  clippingDocument: "Web clipping",
  legacyIntegrity: "legacy integrity",
  openDocument: "Open paper",
  addFavorite: "Add to favorites",
  removeFavorite: "Remove from favorites",
  librarySettings: "Local library",
  librarySettingsCopy: "Only validated packages are listed. Source files stay unchanged.",
  mineruSettings: "MinerU API Token",
  mineruSettingsCopy: "Required only for remote PDF extraction. Reading existing papers and importing clippings do not require a Token.",
  mineruRemoteNotice: "PDF content is sent to the MinerU service when you explicitly start remote extraction. Usage and fees belong to your MinerU account.",
  createMineruToken: "Create Token on MinerU",
  tokenPlaceholder: "Paste MinerU Token",
  saveToken: "Save securely",
  removeToken: "Remove from this device",
  tokenConfigured: "Configured in operating-system protected storage",
  tokenNotConfigured: "Not configured",
  tokenSaved: "Token saved securely. It will be verified by the first supported extraction request.",
  tokenRemoved: "Token removed from this device.",
  settingsError: "Could not update settings",
  loadingLibrary: "Checking the local library…",
  setupIntro: "Complete these steps in order. Existing local papers remain readable even when MinerU is unavailable.",
  setupLibraryTitle: "1. Choose a local library",
  setupLibraryCopy: "Paper2MD publishes only validated packages into this folder.",
  setupTokenTitle: "2. Add your MinerU Token",
  setupTokenCopy: "Create a Token on MinerU, then store it securely on this device.",
  setupConvertTitle: "3. Convert a PDF",
  setupConvertCopy: "When the first two steps are ready, use New extraction.",
  setupComplete: "Ready",
  setupRequired: "Required",
  conversionTitle: "Convert a PDF",
  conversionCopy: "Choose one common preset. Paper2MD validates the result before it appears in your library.",
  conversionPreset: "Common preset",
  presetRecommended: "Recommended · research paper",
  presetFast: "Fast · simple digital PDF",
  presetScanned: "Scanned / Chinese PDF",
  presetCustom: "Custom advanced settings",
  presetRecommendedCopy: "Best default for English research papers with figures, formulas, or multi-column layouts.",
  presetFastCopy: "Uses the standard pipeline for clean, born-digital English PDFs.",
  presetScannedCopy: "Uses VLM, Chinese + English recognition, and OCR for scanned pages.",
  presetCustomCopy: "Uses the detailed MinerU values selected below.",
  advancedSettings: "Advanced settings",
  mineruDetails: "MinerU details",
  localTools: "Local developer workflows",
  localToolsReady: "An external Paper2MD CLI is available. These tools write to a separately selected output folder.",
  localToolsUnavailable: "Not installed in this desktop build. Use MinerU extraction; these controls are available only when an external Paper2MD CLI is configured.",
  readinessReadyTitle: "Ready to convert",
  readinessReadyCopy: "Library, protected Token storage, MinerU Token, network, and atomic publishing checks passed.",
  readinessWarningTitle: "Setup complete · check the warnings",
  readinessWarningCopy: "You can try the conversion, but one or more system checks need attention below.",
  readinessRequiredTitle: "Finish setup first",
  readinessRequiredCopy: "Choose a library and add a MinerU Token before selecting a PDF.",
  openSetup: "Open setup",
  startRemote: "Choose PDF and start conversion",
  selfCheck: "System check",
  rerunSelfCheck: "Run again",
  checkingSelfCheck: "Checking…",
  tasks: "Paper2MD tasks",
  taskCopy: "Use your MinerU account for remote precision extraction, or run a local reviewed workflow.",
  remotePrivacy: "Starting MinerU extraction uploads the selected PDF only after a separate confirmation.",
  remoteModel: "MinerU model",
  pipelineModel: "Pipeline (standard documents)",
  vlmModel: "VLM (complex layouts)",
  documentLanguage: "Document language",
  englishLanguage: "English",
  chineseLanguage: "Chinese + English",
  enableOcr: "Enable OCR for scanned PDFs",
  extraction: "Extraction",
  reviewInput: "Review input",
  references: "References",
  evidence: "Evidence",
  includeSourcePdf: "Include source PDF",
  startReviewed: "Start reviewed layout",
  processDirect: "Process PDF (direct)",
  rightPane: "Reference pane",
  originalPdf: "Original PDF",
  imagesAndCaptions: "Images & captions",
  pdfPreview: "PDF preview",
  previewEmpty: "Open an existing result folder with a source PDF, or choose a PDF to start a conversion.",
  previewNoSource: "No source PDF was found in the selected result folder.",
  previewLoadFailed: "The source PDF in this result folder could not be opened.",
  noTasks: "No conversion tasks yet.",
  directConversion: "Direct conversion",
  remoteConversion: "MinerU precision",
  reviewed: "Reviewed",
  recovered: "recovered",
  openResult: "Open result",
  showFiles: "Show files",
  openReviewFolder: "Open review folder",
  importRoi: "Import confirmed ROI",
  validateBuild: "Validate & build",
  cancel: "Cancel",
  retry: "Retry",
  removeRecord: "Remove record",
  selecting: "Selecting…",
  workflowRequest: "Workflow request",
  standard: "Standard",
  fast: "Fast",
  forensic: "Forensic",
  visualDirect: "Visual direct",
  candidateAssisted: "Candidate assisted",
  keep: "Keep",
  separate: "Separate",
  omit: "Omit",
  minimal: "Minimal",
  full: "Full",
  queued: "queued",
  running: "running",
  awaitingReview: "awaiting review",
  succeeded: "succeeded",
  failed: "failed",
  cancelled: "cancelled"
} as const;

type DesktopCopyKey = keyof typeof ENGLISH;

const CHINESE: Record<DesktopCopyKey, string> = {
  appName: "Paper2MD",
  newExtraction: "新建解析",
  library: "文库",
  favorites: "我的收藏",
  settings: "设置",
  searchLibrary: "搜索论文",
  allDocuments: "全部文档",
  favoriteDocuments: "收藏文档",
  chooseLibrary: "选择论文库",
  changeLibrary: "更换论文库",
  revealLibrary: "在资源管理器中显示",
  noLibrary: "请选择一个本地 Paper2MD 论文库；这里只显示通过校验的论文。",
  emptyLibrary: "当前论文库中还没有已发布并通过校验的论文。",
  emptyFavorites: "收藏的论文会显示在这里。",
  noSearchResults: "没有符合当前搜索的论文。",
  libraryTruncated: "当前显示前 500 篇已验证论文。",
  mineruDocument: "MinerU 内容包",
  clippingDocument: "网页剪藏",
  legacyIntegrity: "旧版完整性绑定",
  openDocument: "打开论文",
  addFavorite: "添加到收藏",
  removeFavorite: "从收藏中移除",
  librarySettings: "本地论文库",
  librarySettingsCopy: "只列出通过校验的内容包；源文件保持不变。",
  mineruSettings: "MinerU API Token",
  mineruSettingsCopy: "仅远程 PDF 提取需要 Token；阅读已有论文和导入网页剪藏均不需要。",
  mineruRemoteNotice: "只有在你明确启动远程提取时，PDF 才会发送到 MinerU 服务；调用额度和费用由你的 MinerU 账户承担。",
  createMineruToken: "前往 MinerU 创建 Token",
  tokenPlaceholder: "粘贴 MinerU Token",
  saveToken: "安全保存",
  removeToken: "从本设备删除",
  tokenConfigured: "已保存到操作系统保护的凭据存储",
  tokenNotConfigured: "尚未配置",
  tokenSaved: "Token 已安全保存，将在首次受支持的提取请求中验证。",
  tokenRemoved: "Token 已从本设备删除。",
  settingsError: "无法更新设置",
  loadingLibrary: "正在检查本地论文库…",
  setupIntro: "请按顺序完成以下步骤。即使 MinerU 暂时不可用，已有本地论文仍可正常阅读。",
  setupLibraryTitle: "1. 选择本地论文库",
  setupLibraryCopy: "Paper2MD 只会把通过校验的内容包发布到此目录。",
  setupTokenTitle: "2. 添加 MinerU Token",
  setupTokenCopy: "前往 MinerU 创建 Token，然后安全保存到本设备。",
  setupConvertTitle: "3. 转换 PDF",
  setupConvertCopy: "前两项完成后，点击“新建解析”即可开始。",
  setupComplete: "已完成",
  setupRequired: "待完成",
  conversionTitle: "转换 PDF",
  conversionCopy: "只需选择一个常用预设；结果通过本地校验后才会出现在论文库中。",
  conversionPreset: "常用预设",
  presetRecommended: "推荐 · 英文科研论文",
  presetFast: "快速 · 简单数字版 PDF",
  presetScanned: "扫描版 / 中文 PDF",
  presetCustom: "自定义高级设置",
  presetRecommendedCopy: "适合包含图表、公式或多栏版式的英文科研论文，建议优先使用。",
  presetFastCopy: "适合排版简单、文字可复制的英文数字版 PDF。",
  presetScannedCopy: "启用 VLM、中英识别和 OCR，适合扫描页或中文论文。",
  presetCustomCopy: "使用下方高级设置中手动选择的 MinerU 参数。",
  advancedSettings: "高级设置",
  mineruDetails: "MinerU 详细参数",
  localTools: "本地开发者工作流",
  localToolsReady: "已检测到外部 Paper2MD CLI；这些工具会写入另行选择的输出目录。",
  localToolsUnavailable: "当前桌面安装包未包含此工具。请使用 MinerU 转换；仅在配置外部 Paper2MD CLI 后才可使用这些按钮。",
  readinessReadyTitle: "已准备好转换",
  readinessReadyCopy: "论文库、凭据保护、MinerU Token、网络和原子发布检查均已通过。",
  readinessWarningTitle: "设置已完成 · 请查看警告",
  readinessWarningCopy: "可以尝试转换，但下方仍有一项或多项系统检查需要处理。",
  readinessRequiredTitle: "请先完成设置",
  readinessRequiredCopy: "选择论文库并添加 MinerU Token 后，才能选择 PDF。",
  openSetup: "打开设置引导",
  startRemote: "选择 PDF 并开始转换",
  selfCheck: "系统自检",
  rerunSelfCheck: "重新检查",
  checkingSelfCheck: "检查中…",
  tasks: "Paper2MD 任务",
  taskCopy: "可使用自己的 MinerU 账户进行远程精准提取，也可运行本地审阅式工作流。",
  remotePrivacy: "只有再次明确确认后，所选 PDF 才会上传到 MinerU。",
  remoteModel: "MinerU 模型",
  pipelineModel: "Pipeline（标准文档）",
  vlmModel: "VLM（复杂版式）",
  documentLanguage: "文档语言",
  englishLanguage: "英文",
  chineseLanguage: "中文 + 英文",
  enableOcr: "为扫描版 PDF 启用 OCR",
  extraction: "提取配置",
  reviewInput: "审阅输入",
  references: "参考文献",
  evidence: "证据级别",
  includeSourcePdf: "包含原始 PDF",
  startReviewed: "启动审阅式布局",
  processDirect: "直接处理 PDF",
  rightPane: "参考面板",
  originalPdf: "原始 PDF",
  imagesAndCaptions: "图片与图注",
  pdfPreview: "PDF 预览",
  previewEmpty: "打开包含原 PDF 的已有结果目录，或选择 PDF 开始新的转换。",
  previewNoSource: "所选结果目录中未找到可预览的原 PDF。",
  previewLoadFailed: "无法打开结果目录中的原 PDF。",
  noTasks: "暂无转换任务。",
  directConversion: "直接转换",
  remoteConversion: "MinerU 精准提取",
  reviewed: "审阅式布局",
  recovered: "已恢复",
  openResult: "打开结果",
  showFiles: "显示文件",
  openReviewFolder: "打开审阅文件夹",
  importRoi: "导入已确认 ROI",
  validateBuild: "校验并构建",
  cancel: "取消",
  retry: "重试",
  removeRecord: "移除记录",
  selecting: "正在选择…",
  workflowRequest: "工作流请求",
  standard: "标准",
  fast: "快速",
  forensic: "取证级",
  visualDirect: "视觉直接审阅",
  candidateAssisted: "候选框辅助",
  keep: "保留",
  separate: "分离",
  omit: "省略",
  minimal: "最少",
  full: "完整",
  queued: "排队中",
  running: "运行中",
  awaitingReview: "等待审阅",
  succeeded: "已完成",
  failed: "失败",
  cancelled: "已取消"
};

const COPY: Record<ReaderLocale, Record<DesktopCopyKey, string>> = { en: ENGLISH, "zh-CN": CHINESE };

export function desktopText(locale: ReaderLocale, key: DesktopCopyKey): string {
  return COPY[locale][key];
}

const SELF_CHECK_ENGLISH: Record<DesktopSelfCheckItem["code"], string> = {
  LIBRARY_READY: "Local library is writable",
  LIBRARY_NOT_CONFIGURED: "Choose a local library",
  LIBRARY_NOT_WRITABLE: "The selected library is not writable",
  CREDENTIALS_READY: "Operating-system credential protection is available",
  CREDENTIALS_UNAVAILABLE: "Protected credential storage is unavailable",
  TOKEN_READY: "MinerU Token is configured",
  TOKEN_NOT_CONFIGURED: "Add a MinerU Token",
  TOKEN_UNREADABLE: "The saved Token cannot be read securely",
  MINERU_REACHABLE: "MinerU submission API is reachable; the upload destination is checked during conversion",
  MINERU_UNREACHABLE: "MinerU submission API cannot be reached right now",
  ATOMIC_PUBLISH_READY: "Staging and atomic publishing are available",
  ATOMIC_PUBLISH_UNAVAILABLE: "Atomic publication check failed",
  LOCAL_CLI_READY: "Optional local Paper2MD CLI is available",
  LOCAL_CLI_UNAVAILABLE: "Optional local Paper2MD CLI is not installed"
};

const SELF_CHECK_CHINESE: Record<DesktopSelfCheckItem["code"], string> = {
  LIBRARY_READY: "本地论文库可写",
  LIBRARY_NOT_CONFIGURED: "请选择本地论文库",
  LIBRARY_NOT_WRITABLE: "所选论文库不可写",
  CREDENTIALS_READY: "操作系统凭据保护可用",
  CREDENTIALS_UNAVAILABLE: "操作系统凭据保护不可用",
  TOKEN_READY: "MinerU Token 已配置",
  TOKEN_NOT_CONFIGURED: "请添加 MinerU Token",
  TOKEN_UNREADABLE: "无法安全读取已保存的 Token",
  MINERU_REACHABLE: "MinerU 提交接口可连接；上传地址会在转换时验证",
  MINERU_UNREACHABLE: "当前无法连接 MinerU 提交接口",
  ATOMIC_PUBLISH_READY: "暂存与原子发布可用",
  ATOMIC_PUBLISH_UNAVAILABLE: "原子发布检查失败",
  LOCAL_CLI_READY: "可选的本地 Paper2MD CLI 可用",
  LOCAL_CLI_UNAVAILABLE: "未安装可选的本地 Paper2MD CLI"
};

export function localizedSelfCheck(item: DesktopSelfCheckItem, locale: ReaderLocale): string {
  return (locale === "zh-CN" ? SELF_CHECK_CHINESE : SELF_CHECK_ENGLISH)[item.code];
}

const CHINESE_MESSAGES: Record<string, string> = {
  "Conversion finished": "转换完成",
  "Review content-roi.json and page ROI previews, then import the confirmed ROI": "请审阅 content-roi.json 和逐页 ROI 预览，然后导入已确认 ROI",
  "All page layouts passed; building the reviewed package": "所有页面布局均已通过，正在构建审阅式内容包",
  "Reviewed layout package finished": "审阅式布局内容包已完成",
  "Cancelled by user": "用户已取消",
  "Retrying direct conversion": "正在重试直接转换",
  "ROI proposal is ready for confirmation": "ROI 提案已可确认",
  "Retrying the ROI proposal": "正在重试 ROI 提案",
  "Retrying layout review preparation": "正在重试布局审阅准备",
  "Retrying layout validation and package build": "正在重试布局校验和内容包构建",
  "Paper2MD is processing the PDF": "Paper2MD 正在处理 PDF",
  "Preparing the authorized PDF for remote MinerU extraction": "正在准备已获授权的 PDF，以进行远程 MinerU 提取",
  "Requesting a protected upload destination from MinerU": "正在向 MinerU 申请受保护的上传地址",
  "Uploading the explicitly authorized PDF to MinerU": "正在将明确授权的 PDF 上传到 MinerU",
  "Waiting for MinerU to start the extraction": "正在等待 MinerU 启动提取任务",
  "MinerU accepted the PDF and is extracting its contents": "MinerU 已接收 PDF，正在提取内容",
  "Downloading the completed MinerU result into isolated staging": "正在将 MinerU 完成结果下载到隔离暂存区",
  "Building deterministic visual contracts and validating the staged package": "正在构建确定性视觉契约并校验暂存内容包",
  "Validation passed; atomically publishing the immutable reading package": "校验通过，正在原子发布不可变阅读包",
  "MinerU extraction passed validation and was published to the local library": "MinerU 提取已通过校验并发布到本地论文库",
  "Cancelled locally; MinerU may finish its already submitted remote task, but Paper2MD will not publish it": "已在本地取消；MinerU 可能继续完成已提交任务，但 Paper2MD 不会发布其结果",
  "MinerU rejected the saved Token; update it in Settings": "MinerU 拒绝了已保存的 Token；请在设置中更新",
  "The MinerU account has insufficient quota for this extraction": "当前 MinerU 账户额度不足，无法完成此次提取",
  "The PDF exceeds MinerU's file-size limit": "PDF 超出 MinerU 文件大小限制",
  "The PDF exceeds MinerU's page limit": "PDF 超出 MinerU 页数限制",
  "MinerU could not find the submitted extraction task": "MinerU 找不到已提交的提取任务",
  "MinerU could not complete this extraction": "MinerU 无法完成此次提取",
  "Remote extraction or deterministic package validation failed; no incomplete package was published": "远程提取或确定性内容包校验失败；未发布任何不完整内容包",
  "Could not reach the MinerU service; check the network and try again": "无法连接 MinerU 服务；请检查网络后重试",
  "MinerU returned malformed JSON": "MinerU 返回了无法解析的响应",
  "MinerU returned an invalid API envelope": "MinerU 返回了无效的 API 响应",
  "MinerU returned no response data": "MinerU 响应中没有可用数据",
  "Preparing a non-destructive content ROI proposal": "正在准备非破坏性的正文 ROI 提案",
  "Confirmed ROI imported; preparing per-page visual review tasks": "已导入确认 ROI，正在准备逐页视觉审阅任务",
  "Checking every page review result": "正在检查每一页的审阅结果",
  "Interrupted when the desktop app closed; retry from the recorded stage": "桌面应用关闭时任务被中断，可从已记录阶段重试",
  "Recovered completed direct conversion": "已恢复完成的直接转换",
  "Direct conversion was interrupted; retry only after removing any partial output": "直接转换曾被中断；移除残留的部分输出后方可重试",
  "Recovered completed reviewed package": "已恢复完成的审阅式内容包",
  "Layout apply was interrupted; partial output must be inspected and removed before retry": "布局应用曾被中断；重试前必须检查并移除部分输出",
  "Recovered layout review files, but the source PDF is unavailable": "已恢复布局审阅文件，但源 PDF 不可用",
  "Layout preparation was interrupted; remove any partial 02-layout-review folder, then retry": "布局准备曾被中断；请移除残留的 02-layout-review 文件夹后重试",
  "Confirmed ROI was recovered, but the source PDF is unavailable": "已恢复确认 ROI，但源 PDF 不可用",
  "Recovered ROI proposal; review and import a confirmed ROI": "已恢复 ROI 提案；请审阅并导入确认 ROI",
  "Recovered ROI proposal, but the source PDF is unavailable": "已恢复 ROI 提案，但源 PDF 不可用",
  "ROI preparation was interrupted; remove any partial 01-roi-proposal folder, then retry": "ROI 准备曾被中断；请移除残留的 01-roi-proposal 文件夹后重试",
  "Reviewed task cannot resume because the source PDF is unavailable": "源 PDF 不可用，无法恢复审阅任务"
};

export function localizedTaskMessage(task: ConversionTask, locale: ReaderLocale): string {
  if (task.errorCode === "MINERU_NETWORK_ERROR") {
    return locale === "zh-CN"
      ? "这是旧版未细分的网络错误；移除记录并重新转换后可获得精确诊断"
      : "This earlier attempt stored only a generic network error; remove it and start a new conversion for precise diagnostics";
  }
  if (locale === "en") return task.message;
  const transportErrors: Record<string, string> = {
    MINERU_API_DNS_ERROR: "无法解析 MinerU 提交接口；请检查 DNS 或网络过滤",
    MINERU_API_TLS_ERROR: "无法与 MinerU 提交接口建立可信 TLS 连接",
    MINERU_API_TIMEOUT: "连接 MinerU 提交接口超时",
    MINERU_API_CONNECTION_FAILED: "无法连接 MinerU 提交接口；请检查网络后重试",
    MINERU_UPLOAD_DNS_ERROR: "无法解析 MinerU 上传地址；请检查 DNS 或网络过滤",
    MINERU_UPLOAD_TLS_ERROR: "无法与 MinerU 上传地址建立可信 TLS 连接",
    MINERU_UPLOAD_TIMEOUT: "连接 MinerU 上传地址超时",
    MINERU_UPLOAD_CONNECTION_FAILED: "无法连接 MinerU 上传地址；请检查网络后重试"
  };
  if (task.errorCode && transportErrors[task.errorCode]) return transportErrors[task.errorCode];
  const exact = CHINESE_MESSAGES[task.message];
  if (exact) return exact;
  const ready = task.message.match(/^(\d+) page review tasks are ready; add final-layout\.json to every page$/);
  if (ready) return `${ready[1]} 个页面审阅任务已就绪；请为每页添加 final-layout.json`;
  const validating = task.message.match(/^Validating page (\d+) of (\d+)$/);
  if (validating) return `正在校验第 ${validating[1]}/${validating[2]} 页`;
  const recovered = task.message.match(/^Recovered (\d+) page review tasks; confirm final-layout\.json files before building$/);
  if (recovered) return `已恢复 ${recovered[1]} 个页面审阅任务；构建前请确认所有 final-layout.json`;
  const mineruProgress = task.message.match(/^MinerU is extracting page (\d+) of (\d+)$/);
  if (mineruProgress) return `MinerU 正在提取第 ${mineruProgress[1]}/${mineruProgress[2]} 页`;
  return task.message;
}

export function localizedTaskStage(task: ConversionTask, locale: ReaderLocale): string {
  if (task.workflow === "mineru-remote" && task.errorCode === "MINERU_NETWORK_ERROR") {
    return locale === "zh-CN" ? "旧版上传阶段（未细分）" : "legacy upload stage (not differentiated)";
  }
  const stages: Partial<Record<ConversionTask["stage"], { en: string; "zh-CN": string }>> = {
    "remote-allocate": { en: "requesting upload address", "zh-CN": "申请上传地址" },
    "remote-upload": { en: "uploading PDF", "zh-CN": "上传 PDF" },
    "remote-extract": { en: "extracting", "zh-CN": "提取中" },
    "remote-download": { en: "downloading result", "zh-CN": "下载结果" },
    "remote-validate": { en: "validating package", "zh-CN": "校验内容包" },
    "remote-publish": { en: "publishing package", "zh-CN": "发布内容包" }
  };
  return stages[task.stage]?.[locale] ?? task.stage;
}

export function localizedTaskState(task: ConversionTask, locale: ReaderLocale): string {
  const keys = {
    queued: "queued",
    running: "running",
    "awaiting-review": "awaitingReview",
    succeeded: "succeeded",
    failed: "failed",
    cancelled: "cancelled"
  } as const;
  return desktopText(locale, keys[task.state]);
}
